export const groups = {
  products: {
    label: "Products",
    href: "/products",
    kicker: "Product Suite",
    title: "Enterprise AI products for every operational workflow",
    desc: "Algonox brings together AI, low-code automation, intelligent document processing, workflow orchestration, RPA, and analytics in one connected product ecosystem.",
    items: [
      ["Spectra", "/spectra", "Operational intelligence for complex enterprise signals and business data streams.", "SP"],
      ["Sweet Hello", "/sweet-hello", "Conversational engagement automation for always-on customer and employee journeys.", "SH"],
      ["IRIS", "/iris", "Recognition and insight layer for documents, operational data, and process intelligence.", "IR"],
      ["ACE", "/ace", "Low-code Enterprise AI platform for rapid end-to-end process automation.", "AC"],
      ["Glide", "/glide", "Conversational AI connected to enterprise workflows, services, and case journeys.", "GL"],
      ["Medsense AI", "/medsense-ai", "Healthcare RCM automation for charge sheets, demographics, claims, and visibility.", "MD"],
      ["Ionic Extraction", "/ionic-extraction", "Intelligent document processing for PDFs, scans, forms, images, and emails.", "IX"],
      ["ACE Cosmos", "/ace-cosmos", "Connected automation command layer across AI, workflows, integrations, and process data.", "CS"],
      ["SmartFlows", "/smartflows", "Visual workflow automation with case management, rules, access control, and approvals.", "SF"],
      ["GEARS", "/gears", "Operational reporting and automation engine for repeatable business outputs.", "GR"],
      ["Lucid Reconciliations", "/lucid-reconciliations", "Automated reconciliation workflows for finance, banking, and shared services.", "LR"],
      ["Instabolt Reports", "/instabolt-reports", "Fast reporting layer for dashboards, structured exports, and business-ready insights.", "IR"],
      ["Splash", "/splash", "Real-time dashboarding, analytics, and operational visibility.", "SL"],
      ["Hertz Email Automation", "/hertz-email", "Cognitive email processing and response automation for high-volume operations.", "HZ"],
      ["PV Automate", "/pv-automate", "Pharmacovigilance automation for adverse event detection and compliance reporting.", "PV"],
      ["Codara", "/codara", "Intelligent code generation and automated process auditing.", "CD"],
      ["RCM Process", "/rcm-process", "End-to-end healthcare revenue cycle management and billing automation.", "RC"],
      ["COSMOS Master Data Management", "/cosmos-mdm", "Connected automation command layer across master data, workflows, and process data.", "MD"],
    ],
  },
  ai: {
    label: "AI Solutions",
    href: "/ai-solutions",
    kicker: "AI Solutions",
    title: "Practical enterprise AI for governed business execution",
    desc: "Build intelligent journeys with AI agents, voice agents, conversational AI, agentic AI, and enterprise-grade AI decisioning.",
    items: [
      ["Sweet Hello", "/sweet-hello", "Conversational engagement automation for always-on customer and employee journeys.", "SH"],
      ["Glide", "/glide", "Conversational AI connected to enterprise workflows, services, and case journeys.", "GL"],
      ["IRIS", "/iris", "Recognition and insight layer for documents, operational data, and process intelligence.", "IR"],
      ["ACE", "/ace", "Low-code Enterprise AI platform for rapid end-to-end process automation.", "AC"],
      ["Voice Agents", "/voice-agents", "AI voice experiences for service, qualification, routing, and guided operations.", "VA"],
      ["AI Agents", "/ai-agents", "Task-aware agents that plan, decide, and execute governed enterprise workflows.", "AA"],
      ["Conversational AI", "/conversational-ai", "Natural language assistants connected to cases, systems, and operational data.", "CA"],
      ["Agentic AI", "/agentic-ai", "Goal-driven AI for multi-step execution, reasoning, orchestration, and follow-up.", "AG"],
      ["Enterprise AI", "/enterprise-ai", "Scalable AI capabilities designed for measurable, secure, enterprise outcomes.", "EA"],
    ],
  },
  automation: {
    label: "Automation Solutions",
    href: "/automation-solutions",
    kicker: "Automation Solutions",
    title: "End-to-end automation from intake to action",
    desc: "Automate complete process journeys with IDP, visual workflow automation, RPA, decision intelligence, and human-in-the-loop governance.",
    items: [
      ["Spectra", "/spectra", "Operational intelligence for complex enterprise signals and business data streams.", "SP"],
      ["Codara", "/codara", "Intelligent code generation and automated process auditing.", "CD"],
      ["Splash", "/splash", "Real-time dashboarding, analytics, and operational visibility.", "SL"],
      ["ACE", "/ace", "Low-code Enterprise AI platform for rapid end-to-end process automation.", "AC"],
      ["Intelligent Document Processing (IDP)", "/intelligent-document-processing", "Capture, classify, extract, validate, and export high-volume documents.", "ID"],
      ["Workflow Automation", "/workflow-automation", "Design visual workflows for teams, bots, approvals, rules, and cases.", "WF"],
      ["Process Automation", "/process-automation", "Automate business processes from data intake through reporting and export.", "PA"],
      ["RPA Solutions", "/rpa-solutions", "Connect bots, legacy systems, and repetitive tasks for hands-free execution.", "RP"],
      ["Decision Intelligence", "/decision-intelligence", "Use AI, rules, prioritization, and analytics to accelerate decisions.", "DI"],
      ["Human-in-the-Loop Automation", "/human-in-the-loop-automation", "Bring people into exception handling, review, approvals, and quality checks.", "HL"],
    ],
  },
  industries: {
    label: "Industries",
    href: "/industries",
    kicker: "Industries",
    title: "Built for high-volume, compliance-driven operations",
    desc: "Algonox supports complex workflows across banking, finance, healthcare, pharmaceuticals, insurance, retail, media, manufacturing, and logistics operations.",
    items: [
      ["Banking", "/banking", "KYC, AML, fraud operations, lending, reconciliations, and customer servicing.", "BK"],
      ["Financial Services", "/financial-services", "Client onboarding, contract operations, reporting, and regulated workflows.", "FS"],
      ["Finance & Accounting", "/finance-accounting", "Invoice automation, payment posting, reconciliations, reporting, and close support.", "FA"],
      ["Healthcare", "/healthcare", "RCM, claims, authorizations, charge capture, demographics, and analytics.", "HC"],
      ["Pharmaceuticals", "/pharmaceuticals", "Compliant workflows, document operations, case tracking, and critical communications.", "PH"],
      ["Insurance", "/insurance", "Claims intake, underwriting support, policy servicing, fraud signals, and approvals.", "IN"],
      ["Retail & E-commerce", "/retail-ecommerce", "Support, returns, invoice operations, customer intelligence, and fulfillment exceptions.", "RE"],
      ["Logistics & Supply Chain", "/logistics-supply-chain", "Vendor, shipment, invoice, exception, and supply chain document workflows.", "LS"],
      ["RCM", "/rcm", "End-to-end healthcare revenue cycle management and billing automation.", "RC"],
      ["Media", "/media", "Planning, ad ops, subscriber management, and campaign automation.", "MD"],
      ["Manufacturing", "/manufacturing", "Competitive pricing monitoring, intercompany tax, ERP automation, and compliance.", "MF"],
    ],
  },
  usecases: {
    label: "Use Cases",
    href: "/use-cases",
    kicker: "Use Cases",
    title: "Automation patterns for teams that move fast",
    desc: "Apply Algonox automation to customer support, lead qualification, research, KYC, invoices, claims, reconciliations, fraud, and payment operations.",
    items: [
      ["Customer Support Automation", "/customer-support-automation", "Triage, route, respond, resolve, and report across support operations.", "CS"],
      ["Lead Qualification", "/lead-qualification", "Qualify prospects with AI agents, workflow routing, and sales-ready handoffs.", "LQ"],
      ["Market Research", "/market-research", "Collect, classify, structure, and report market intelligence at scale.", "MR"],
      ["Consumer Intelligence", "/consumer-intelligence", "Turn customer feedback, behavior, and signals into operational insights.", "CI"],
      ["KYC & AML", "/kyc-aml", "Identity checks, screening, document review, case routing, and compliance visibility.", "KY"],
      ["Invoice Processing", "/invoice-processing", "Extract, validate, approve, reconcile, and export invoice data.", "IP"],
      ["Claims Processing", "/claims-processing", "Claims intake, document review, routing, adjudication support, and analytics.", "CP"],
      ["Payment Posting", "/payment-posting", "Payment capture, validation, posting, exception handling, and revenue visibility.", "PP"],
      ["Reconciliations", "/reconciliations", "Match transactions, surface exceptions, route review, and close faster.", "RC"],
      ["Fraud Detection", "/fraud-detection", "Detect risk signals, prioritize investigation, and manage fraud cases.", "FD"],
    ],
  },
  solutions: {
    label: "Solutions",
    href: "/solutions",
    kicker: "Solutions",
    title: "Enterprise AI and Intelligent Automation Solutions",
    desc: "Build intelligent journeys with AI agents, voice agents, Conversational AI, IDP, and workflow automation.",
    items: [
      ["Sweet Hello", "/sweet-hello", "Conversational engagement automation.", "SH"],
      ["Glide", "/glide", "Conversational AI connected to workflows.", "GL"],
      ["IRIS", "/iris", "Recognition and insight layer.", "IR"],
      ["ACE", "/ace", "Low-code Enterprise AI platform.", "AC"],
      ["Spectra", "/spectra", "Operational intelligence for complex signals.", "SP"],
      ["Codara", "/codara", "Intelligent code generation and process auditing.", "CD"],
      ["Splash", "/splash", "Real-time dashboarding and analytics.", "SL"],
      ["Voice Agents", "/voice-agents", "AI voice experiences for customer journeys.", "VA"],
      ["AI Agents", "/ai-agents", "Task-aware agents that execute governed workflows.", "AA"],
      ["Conversational AI", "/conversational-ai", "Natural language assistants.", "CA"],
      ["Agentic AI", "/agentic-ai", "Goal-driven AI for multi-step execution.", "AG"],
      ["Enterprise AI", "/enterprise-ai", "Scalable AI capabilities.", "EA"],
      ["Intelligent Document Processing (IDP)", "/intelligent-document-processing", "Extract and validate document data.", "ID"],
      ["Workflow Automation", "/workflow-automation", "Design visual workflows for teams.", "WF"],
      ["Process Automation", "/process-automation", "Automate business processes end-to-end.", "PA"],
      ["RPA Solutions", "/rpa-solutions", "Connect bots and legacy systems.", "RP"],
      ["Decision Intelligence", "/decision-intelligence", "Use AI and rules to accelerate decisions.", "DI"],
      ["Human-in-the-Loop Automation", "/human-in-the-loop-automation", "Bring people into exception handling.", "HL"],
    ]
  },
  banking: {
    label: "Banking",
    href: "/banking",
    kicker: "Banking",
    title: "AI & Automation for Banking Operations",
    desc: "Accelerate compliance, risk management, and customer operations with enterprise-grade AI.",
    items: [
      ["ACE", "/banking/ace", "Low-code Enterprise AI platform for Rapid Process Automation in Banking.", "AC"],
      ["Voice Agents", "/banking/voice-agents", "AI voice experiences for banking customer support and routing.", "VA"],
      ["AI Colleague Studio", "/banking/ai-colleague-studio", "Departmental AI colleagues for credit risk, loan verification, and compliance.", "CS"],
    ],
  },
  healthcare: {
    label: "Healthcare",
    href: "/healthcare",
    kicker: "Healthcare",
    title: "Intelligent Automation for Healthcare",
    desc: "Streamline patient and provider operations, billing, and scheduling workflows.",
    items: [
      ["ACE", "/healthcare/ace", "Low-code Enterprise AI platform for rapid clinical and administrative automation.", "AC"],
      ["Voice Agents", "/healthcare/voice-agents", "AI voice experiences for appointment scheduling and patient inquiries.", "VA"],
      ["AI Colleague Studio", "/healthcare/ai-colleague-studio", "Enterprise AI colleagues for claims, compliance, and care workflows.", "CS"],
    ],
  },
  pharmaceuticals: {
    label: "Pharmaceuticals",
    href: "/pharmaceuticals",
    kicker: "Pharmaceuticals",
    title: "AI Compliance & Operations in Pharma",
    desc: "Ensure compliant workflows, clinical trial management, and quality control automation.",
    items: [
      ["ACE", "/pharmaceuticals/ace", "Low-code Enterprise AI platform for regulatory and lab data processing.", "AC"],
      ["Voice Agents", "/pharmaceuticals/voice-agents", "AI voice experiences for study site communication and trial logistics.", "VA"],
      ["AI Colleague Studio", "/pharmaceuticals/ai-colleague-studio", "AI colleagues for compliance auditing and drug safety reporting.", "CS"],
    ],
  },
  rcm: {
    label: "RCM",
    href: "/rcm",
    kicker: "RCM",
    title: "Revenue Cycle Management Automation",
    desc: "Automate charge capture, demographics, claims posting, and denials management.",
    items: [
      ["ACE", "/rcm/ace", "Low-code Enterprise AI platform for RCM workflow and billing orchestration.", "AC"],
      ["Voice Agents", "/rcm/voice-agents", "AI voice experiences for patient billing calls and collection follow-ups.", "VA"],
      ["AI Colleague Studio", "/rcm/ai-colleague-studio", "AI colleagues for claim scrubbing, audit, and eligibility verification.", "CS"],
    ],
  },
  media: {
    label: "Media",
    href: "/media",
    kicker: "Media",
    title: "Cognitive Automation for Media & Publishing",
    desc: "Automate campaign planning, content tagging, and advertiser service workflows.",
    items: [
      ["ACE", "/media/ace", "Low-code Enterprise AI platform for content distribution and ad ops.", "AC"],
      ["Voice Agents", "/media/voice-agents", "AI voice experiences for subscriber support and interactive campaigns.", "VA"],
      ["AI Colleague Studio", "/media/ai-colleague-studio", "AI colleagues for media planning, scheduling, and analytics auditing.", "CS"],
    ],
  },
  "finance-accounting": {
    label: "Finance & Accounting",
    href: "/finance-accounting",
    kicker: "Finance & Accounting",
    title: "Automated Financial & Accounting Operations",
    desc: "Close the books faster with invoice automation, reconciliations, and reporting.",
    items: [
      ["ACE", "/finance-accounting/ace", "Low-code Enterprise AI platform for accounts payable and TDS matching.", "AC"],
      ["Voice Agents", "/finance-accounting/voice-agents", "AI voice experiences for vendor inquiries and collections.", "VA"],
      ["AI Colleague Studio", "/finance-accounting/ai-colleague-studio", "AI colleagues for reconciliation analysis and cash flow forecasting.", "CS"],
    ],
  },
  insurance: {
    label: "Insurance",
    href: "/insurance",
    kicker: "Insurance",
    title: "Enterprise AI for Insurance Operations",
    desc: "Accelerate underwriting support, claims intake, and contract analysis.",
    items: [
      ["ACE", "/insurance/ace", "Low-code Enterprise AI platform for claims adjudication and policy ingestion.", "AC"],
      ["Voice Agents", "/insurance/voice-agents", "AI voice experiences for claims intake and policy verification.", "VA"],
      ["AI Colleague Studio", "/insurance/ai-colleague-studio", "AI colleagues for risk assessment and contract compliance.", "CS"],
    ],
  },
  manufacturing: {
    label: "Manufacturing",
    href: "/manufacturing",
    kicker: "Manufacturing",
    title: "AI-Powered Manufacturing & Supply Chain",
    desc: "Automate intercompany tax, ERP entries, price monitoring, and analytics.",
    items: [
      ["ACE", "/manufacturing/ace", "Low-code Enterprise AI platform for logistics and inventory operations.", "AC"],
      ["Voice Agents", "/manufacturing/voice-agents", "AI voice experiences for distributor support and order dispatch.", "VA"],
      ["AI Colleague Studio", "/manufacturing/ai-colleague-studio", "AI colleagues for parts matching, quality logs, and supply audits.", "CS"],
    ],
  },
  others: {
    label: "Others",
    href: "/others",
    kicker: "Other Industries",
    title: "Tailored AI solutions for other high-growth sectors",
    desc: "Algonox delivers custom enterprise AI and intelligent automation solutions across BPO, Legal, HR, ITES, Energy, and Telecommunications.",
    items: [
      ["Financial Services", "/financial-services", "Client onboarding, contract operations, reporting, and regulated workflows.", "FS"],
      ["Retail & E-commerce", "/retail-ecommerce", "Support, returns, invoice operations, customer intelligence, and fulfillment exceptions.", "RE"],
      ["Logistics & Supply Chain", "/logistics-supply-chain", "Vendor, shipment, invoice, exception, and supply chain document workflows.", "LS"],
      ["ITES", "/ites", "Incident management, ticket resolution, and contact center process automation.", "IT"],
      ["BPO & Outsourcing", "/bpo-outsourcing", "Automated customer responses, email automation, and business process outsourcing.", "BP"],
      ["Legal Operations", "/legal-operations", "Artificial intelligence-based legal research and predicting case outcomes.", "LG"],
      ["HR & Corporate Services", "/hr-corporate", "Payroll process automation, onboarding verification, and personnel tracking.", "HR"],
      ["Energy & Utilities", "/energy-utilities", "Asset performance management, grid analytics, and sensor monitoring.", "EN"],
      ["Telecommunications", "/telecommunications", "Hardware ticket resolution and porting/verifying customer information.", "TC"],
    ],
  },
};

export const corePages = [
  {
    path: "/",
    title: "Algonox | Enterprise AI and Intelligent Automation",
    eyebrow: "Enterprise AI · Hyperautomation · Cognitive Automation",
    h1: "Automate Any Process End-to-End with Enterprise AI",
    desc: "Algonox Cognitive Engine helps businesses reimagine operations through AI, machine learning, RPA, intelligent document processing, and low-code automation.",
    home: true,
  },
  {
    path: "/about",
    title: "About Algonox",
    eyebrow: "Company",
    h1: "Create process expressways with intelligent automation",
    desc: "Algonox helps enterprises modernize operations with AI, low-code automation, cognitive automation, intelligent document processing, workflow orchestration, and analytics.",
  },
  {
    path: "/resources",
    title: "Resources | Algonox",
    eyebrow: "Resources",
    h1: "Ideas for modern enterprise automation teams",
    desc: "Explore intelligent automation thinking across Enterprise AI, IDP, RPA, workflow automation, healthcare RCM, finance operations, and AI agents.",
  },
  {
    path: "/contact",
    title: "Contact Algonox",
    eyebrow: "Schedule a Demo",
    h1: "Build your next process expressway with Algonox",
    desc: "Book a demo to experience how Algonox solutions can help your business reach new heights with Enterprise AI and automation.",
  },
];

export const testimonials = [
  {
    quote: "Algonox has completely transformed our document processing workflows. What used to take days now takes minutes with incredible accuracy.",
    author: "VP of Operations",
    company: "Global Financial Services Firm",
  },
  {
    quote: "The AI agents from Algonox act just like our best employees, handling complex exceptions and freeing up our team for strategic work.",
    author: "Director of Automation",
    company: "Leading Healthcare Provider",
  },
  {
    quote: "Implementing Algonox's cognitive automation platform was a game-changer for our supply chain visibility and reconciliation processes.",
    author: "Chief Information Officer",
    company: "International Logistics Company",
  },
  {
    quote: "We started with a pilot on ACE for automating our credit risk management process. The results it delivered were very enticing that we went ahead and rolled-out multi-phase full-fledged implementation in a record time. We are currently automating 5 other processes as I speak with ACE",
    author: "Leadership Team",
    company: "India’s Top 3 Bank",
  },
];